blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ ì§ˆë¬¸ ë° í† ë¡ 
    url: https://github.com/daepyro/design-system/discussions
    about: ì‚¬ìš© ë°©ë²•, ì•„í‚¤í…ì²˜ ë“±ì— ëŒ€í•œ ì§ˆë¬¸ì€ Discussionsë¥¼ ì´ìš©í•´ì£¼ì„¸ìš”



